default: &default
  adapter: postgresql
  encoding: unicode
  timeout: 5000
  host: <%= Rails.application.credentials.db.dig(:tunnel_logs, :host) %>
  port: <%= Rails.application.credentials.db.dig(:tunnel_logs, :port) %>
  username: <%= Rails.application.credentials.db.dig(:tunnel_logs, :user) %>
  password: <%= Rails.application.credentials.db.dig(:tunnel_logs, :pass) %>

development:
  <<: *default
  database: tunnel_logs_development

test:
  <<: *default
  database: tunnel_logs_test

production:
  <<: *default
  database: tunnel_logs

pc3_rom:
  adapter: postgresql
  database: pc3_production
  host: <%= Rails.application.credentials.db.dig(:pc3, :host) %>
  port: <%= Rails.application.credentials.db.dig(:pc3, :port) %>
  username: <%= Rails.application.credentials.db.dig(:pc3, :user) %>
  password: <%= Rails.application.credentials.db.dig(:pc3, :pass) %>
