default: &default
  adapter: postgresql
  encoding: unicode
  timeout: 5000
#  host: <%#= Rails.application.credentials.db.dig(:ate_eight, :host) %>
#  port: <%#= Rails.application.credentials.db.dig(:ate_eight, :port) %>
#  username: <%#= Rails.application.credentials.db.dig(:ate_eight, :user) %>
#  password: <%#= Rails.application.credentials.db.dig(:ate_eight, :pass) %>

development:
  <<: *default
  database: ate_eight_development

test:
  <<: *default
  database: ate_eight_test

production:
  <<: *default
  database: ate_eight

