default: &default
  adapter: postgresql
  encoding: unicode
  timeout: 5000
  host: <%= ENV['TL_DATABASE_HOST'] %>
  username: <%= ENV['TL_DATABASE_USER'] %>
  password: <%= ENV['TL_DATABASE_PASS'] %>
development:
  <<: *default
  database: tunnel_logs_development

test:
  <<: *default
  database: tunnel_logs_test

production:
  <<: *default
  database: tunnel_logs

pc3_rom:
  adapter: postgresql
  database: pc3_production
  host: <%= ENV['PC3_DATABASE_HOST'] %>
  username: <%= ENV['PC3_DATABASE_USER'] %>
  password: <%= ENV['PC3_DATABASE_PASS'] %>
